default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234567890

development:
  <<: *default
  host: localhost
  database: school_diary_app2

production:
  <<: *default
  encoding: unicode
  pool: 15
  url:  <%= ENV["DATABASE_URL"] %>
  database: school_diary_app2
  password: 1234567890
  username: postgres

test:
  <<: *default
  host: localhost
  database: school_diary_test2